apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  AUTH: mongodb+srv://rekhivansh6_6:Vansh%40123@cluster0.f7gafhc.mongodb.net/auth
  SANDBOX: mongodb+srv://rekhivansh6_6:Vansh%40123@cluster0.f7gafhc.mongodb.net/sandbox
  AI: mongodb+srv://rekhivansh6_6:Vansh%40123@cluster0.f7gafhc.mongodb.net/ai
  REDIS_URL: redis://default:dcFGYgZfbbmAg3yfG4qBByyfriVyVoXw@redis-12695.crce179.ap-south-1-1.ec2.cloud.redislabs.com:12695


---

apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
stringData:
  JWT_SECRET: 81bb77a1c6c764d692bf41987e49fd963cb7bed9d63d2de72cc4185cd8f01e5bd9779cc14c8054cabaefa80a


---
apiVersion: v1
kind: Secret
metadata:
  name: google
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: 100279602149-9vir187pihd5dua1a0nra9iv946aoplm.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secret
type: Opaque
stringData:
  MISTRAL_API_KEY: 3siKDd0Ua4HLgAzu0aXycVJgiUeP4PHu